import Navigation from '@/components/navigation/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/navigation/Footer'
import Image from 'next/image'
import logo from '@/assets/logo-nav.png'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sthapattyan O Nirman',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
   <Link href="/">   <Image className='mx-auto pt-8 hidden xl:block' src={logo} alt='logo' width={80} height={80} /></Link>
   {/* Desktop Navigation  */}
<Navigation />

{/* Mobile Navigation  */}
<div>
</div>
      <div className='pt-5 min-h-calc(100vh-300px)'>{children}</div>
        <Footer />
        </body>
    </html>
  )
}
